FORMAT_FILES=beluga-serial/include/beluga/*.hpp \
	beluga-serial/src/*.cpp \
	beluga-serial/serial/include/serial/core/C-API/*.h \
	beluga-serial/serial/include/serial/core/*.hpp \
	beluga-serial/serial/include/serial/tools/core/*.hpp \
	beluga-serial/serial/include/serial/tools/*.hpp \
	beluga-serial/serial/include/serial/*.hpp \
	beluga-serial/serial/src/core/C-API/*.c \
	beluga-serial/serial/src/core/*.cpp \
	beluga-serial/serial/src/tools/core/*.cpp \
	beluga-serial/serial/src/tools/*.cpp

format:
	clang-format -i $(FORMAT_FILES)