uint8 AT_COMMAND_STARTUWB=0
uint8 AT_COMMAND_STOPUWB=1
uint8 AT_COMMAND_STARTBLE=2
uint8 AT_COMMAND_STOPBLE=3
uint8 AT_COMMAND_ID=4
uint8 AT_COMMAND_BOOTMODE=5
uint8 AT_COMMAND_RATE=6
uint8 AT_COMMAND_CHANNEL=7
uint8 AT_COMMAND_RESET=8
uint8 AT_COMMAND_TIMEOUT=9
uint8 AT_COMMAND_TXPOWER=10
uint8 AT_COMMAND_STREAMMODE=11
uint8 AT_COMMAND_TWRMODE=12
uint8 AT_COMMAND_LEDMODE=13
uint8 AT_COMMAND_REBOOT=14
uint8 AT_COMMAND_PWRAMP=15
uint8 AT_COMMAND_ANTENNA=16
uint8 AT_COMMAND_TIME=17
uint8 AT_COMMAND_DEEPSLEEP=18
uint8 AT_COMMAND_DATARATE=19
uint8 AT_COMMAND_PREAMBLE=20
uint8 AT_COMMAND_PULSERATE=21
uint8 AT_COMMAND_PHR=22
uint8 AT_COMMAND_PAC=23
uint8 AT_COMMAND_SFD=24
uint8 AT_COMMAND_PANID=25

string arg
uint8 at_command
---
string response
