FORMAT_FILES=src/*.c include/*.h DecaDriver/src/*.c DecaDriver/include/*.h src/serial/*.c \
include/serial/*.h src/ble/services/*.c include/ble/services/*.h src/ble/*.c include/ble/*.h

format:
	clang-format -i $(FORMAT_FILES)
