//
// Created by tom on 6/25/24.
//

#ifndef BELUGA_THREAD_PRIORITIES_H
#define BELUGA_THREAD_PRIORITIES_H

#ifndef CONFIG_ENABLE_BELUGA_THREADS
#define ENABLE_THREADS   0
#else
#define ENABLE_THREADS   1
#endif

#ifndef CONFIG_ENABLE_COMMANDS
#define ENABLE_COMMANDS  0
#else
#define ENABLE_COMMANDS  1
#define COMMAND_PRIO     CONFIG_BELUGA_COMMANDS_PRIO
#endif

#ifndef CONFIG_ENABLE_LIST
#define ENABLE_LIST      0
#else
#define ENABLE_LIST      1
#define LIST_PRIO CONFIG_BELUGA_LIST_PRIO
#endif

#ifndef CONFIG_ENABLE_RANGING
#define ENABLE_RANGING   0
#else
#define ENABLE_RANGING   1
#define RANGING_PRIO CONFIG_BELUGA_RANGING_PRIO
#endif

#ifndef CONFIG_ENABLE_MONITOR
#define ENABLE_MONITOR   0
#else
#define ENABLE_MONITOR   1
#define MONITOR_PRIO CONFIG_BELUGA_MONITOR_PRIO
#endif

#ifndef CONFIG_ENABLE_RESPONDER
#define ENABLE_RESPONDER 0
#else
#define ENABLE_RESPONDER 1
#define RESPONDER_PRIO CONFIG_BELUGA_RESPONDER_PRIO
#endif

#endif // BELUGA_THREAD_PRIORITIES_H
